name: home_manager_stock_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  adaptive_theme: ^3.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  forui: ^0.5.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
assets:
  - .env